# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-30 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ast_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='blk_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='drb_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='fg_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='fga_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='ft_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='fta_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='orb_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='pf_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='pts_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='stl_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='tov_per_g',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
    ]
