# Generated by Django 3.0.1 on 2020-03-16 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0003_auto_20200315_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='team_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='matchups.Team'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='team_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='matchups.Team'),
        ),
    ]
