# Generated by Django 3.0.1 on 2020-03-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0002_auto_20191230_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.AddField(
            model_name='team',
            name='game_score',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('Celtics', 'Celtics'), ('Hawks', 'Hawks'), ('Warriors', 'Warriors'), ('Hornets', 'Hornets'), ('Bulls', 'Bulls'), ('Cavaliers', 'Cavaliers'), ('Mavericks', 'Mavericks'), ('Nuggets', 'Nuggets'), ('Pistons', 'Pistons'), ('Rockets', 'Rockets'), ('Pacers', 'Pacers'), ('Clippers', 'Clippers'), ('Lakers', 'Lakers'), ('Grizzlies', 'Grizzlies'), ('Heat', 'Heat'), ('Bucks', 'Bucks'), ('Timberwolves', 'Timberwolves'), ('Pelicans', 'Pelicans'), ('Knicks', 'Knicks'), ('Thunder', 'Thunder'), ('Magic', 'Magic'), ('Sixers', 'Sixers'), ('Suns', 'Suns'), ('Kings', 'Kings'), ('Spurs', 'Spurs'), ('Raptors', 'Raptors'), ('Jazz', 'Jazz'), ('Wizards', 'Wizards')], max_length=200),
        ),
    ]
